name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
        - 1.13.4-erlang-24.3.4.16-ubuntu-jammy-20240125
        - 1.14.5-erlang-24.3.4.16-ubuntu-jammy-20240125
        - 1.15.7-erlang-24.3.4.16-ubuntu-jammy-20240125
        - 1.16.1-erlang-24.3.4.16-ubuntu-jammy-20240125
    env:
      FERMO_RUN_INTEGRATION: 1

    steps:
    - name: Set up Earthly
      uses: earthly/actions-setup@v1
    - uses: actions/checkout@v4
    - name: Run tests under ${{matrix.elixirbase}}
      run: earthly -P --ci --build-arg ELIXIR_BASE=${{matrix.elixirbase}} --build-arg COVERALLS_GITHUB=true +test